### ISSUE TITLE
Impossible to register

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/nimforum#100]
I can't get past the captcha validation, I enter the correct answer but it always gives me a `Error: Answer to captcha incorrect!`...

**Comment by euantorano** [comment]
This is a known issue, which is probably caused by CloudFlare caching the captcha images. Usually the recommendation is to try another browser. There is [an open PR](https://github.com/nim-lang/nimforum/pull/98) to change the captcha to use reCAPTCHA to try and fix this issue.

**Comment by dom96** [comment]
Yeah, sorry about this. I will do my best to roll out the reCAPTCHA today.

**Comment by dom96** [comment]
And I've hit a regression... Might need to postpone the rollout of this.

**Comment by dom96** [comment]
reCAPTCHA has been rolled out long ago
