### ISSUE TITLE
Registration confirmation emails not being sent

### ISSUE THREAD

**Issue by flother** [nim-lang/nimforum#101]
I registered for the forum this morning ([profile](https://forum.nim-lang.org/profile/flother)) but five hours later I haven't received the email to allow me to confirm my account. I registered with a Gmail address so there's no unusual setup on my end, and my spam folder is empty. As far as I can tell the email hasn't been sent.

**Comment by dom96** [comment]
Should be fixed now. I also took the liberty of reactivating your account.
