### ISSUE TITLE
Confirmation email gets rejected because hostname in HELO isn't an FQDN

### ISSUE THREAD

**Issue by mjcaley** [nim-lang/nimforum#105]
I tried registering an account and found my mail server was rejecting the message.  

>  postfix/smtpd[10031]: connect from mail.nim-lang.org[46.101.40.62]
>  policyd-spf[10097]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=46.101.40.62; helo=mail; envelope-from=forum@nim-lang.org; receiver=<UNKNOWN>
>  postfix/smtpd[10031]: NOQUEUE: reject: RCPT from mail.nim-lang.org[46.101.40.62]: 504 5.5.2 <mail>: Helo command rejected: need fully-qualified hostname; from=<forum@nim-lang.org> to=<censored@example.com> proto=ESMTP helo=<mail>
>  postfix/smtpd[10031]: disconnect from mail.nim-lang.org[46.101.40.62] ehlo=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=4/6

It gets passed through a Sender Policy Framework check and sees that it's giving the hostname of "mail" as its HELO instead of something like "mail.nim-lang.org".

I tried a telnet into the same mail server and here's the output:

>  \# telnet mail.nim-lang.org 25
>  Trying 46.101.40.62...
>  Connected to mail.nim-lang.org.
>  Escape character is '^]'.
>  220 mail ESMTP Postfix (Ubuntu)
>  EHLO censored.example.com
>  250-mail
>  250-PIPELINING
>  250-SIZE 10240000
>  250-VRFY
>  250-ETRN
>  250-STARTTLS
>  250-AUTH PLAIN LOGIN
>  250-ENHANCEDSTATUSCODES
>  250-8BITMIME
>  250 DSN
>  quit
>  221 2.0.0 Bye

You can see the first line after my EHLO reports "mail" again.

I think if the hostname is changed to the fully qualified domain name it'll fix the rejections.

**Comment by dom96** [comment]
Fixed :)

**Comment by dom96** [comment]
Let me know if it helps. (You can try resetting your password)

**Comment by mjcaley** [comment]
Works perfect!  Thanks a lot!
