### ISSUE TITLE
Latest build broken: See extra localhost.local/public/css & localhost.local/public/images

### ISSUE THREAD

**Issue by riptex** [nim-lang/nimforum#149]
It looks like some string substitution is failing during build causing final output to be missing two files. 

public/images/logo.png
public/css/custom-style.scss

which got dumped in

/localhost.local/public/images/logo.png
/localhost.local/public/css/custom-style.scss

This causes startup failure when executing ./forum

cheers, 

D

**Comment by dom96** [comment]
What's the error? Are you using the release archive? Please elaborate.

**Comment by dom96** [comment]
ping @riptex

**Comment by Yardanico** [comment]
@dom96 he probably means that there's this folder in github repo:
https://github.com/nim-lang/nimforum/tree/master/localhost.local/public

**Comment by dom96** [comment]
Yeah, but it's supposed to be there.
