### ISSUE TITLE
[Feature Request] Categories/Tags

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/nimforum#169]
As @dom96 mentioned, these are [already partially implemented](https://github.com/nim-lang/nimforum/blob/master/src/frontend/category.nim).

A few niceties would also need to be added in order for these to provide value to users in the forum.

- being able to sort/filter (#168) by tags and/or be able to view only posts with a certain tag in a separate post list view (similar to discourse's [categories view](https://try.discourse.org/categories)).
- being able to request or suggest new categories/tags
- being able to search and/or view all tags for useful ones
- This one is more of a separate feature after tags, and definitely not required. "meta tags", or tags are just a list of multiple tags.

**Meta tags**

These would make it easier to find posts in the category view that may have several tags that are somewhat obscure. Basically, they give a label to multiple tags that is more useful than the individual tags themselves and allows them to be searched.
For example a bunch of tags could be: "tutorial", "macros", "recommended" with a meta tag of "Recommended Macro Tutorials". When a user is looking for "macro" in the tag search, this result will also popup (instead of just "macros") and they discover other useful tags like "tutorial" and "recommended". This is a bit of a lame example, since all of the tags are also in the meta tag, but I still think it would be useful.

I'd say the first three would satisfy this issue fine, and the last one is more of an "Add on" feature once tags are working.

**Comment by jyapayne** [comment]
@dom96 I'm currently working on this, so just be aware :)

One thing that I noticed that discord has is both Categories and Tags. Categories seem to be things that the site moderators can add and Tags seem to be user addable. I think both would be nice to have, especially since then a user could have his/her own "series" that are marked by custom tags that could then be filtered and searched. What are your thoughts?

**Comment by dom96** [comment]
I think categories only for now will be good enough. I doubt more than 1% of our users will create their own tags.

**Comment by jyapayne** [comment]
This should be fulfilled completely in https://github.com/nim-lang/nimforum/pull/229
