### ISSUE TITLE
how to setup mail sender fromAddr?

### ISSUE THREAD

**Issue by saggit** [nim-lang/nimforum#190]
Hi, I am sentup a new forum use the guide, when i test the reset password on dashboard,
i get nothing, but  mailjet(email service) dashboard display a pending mail sender `forum@nim-lang.org`, also `forum-setup --setup` did not asked for `fromAddr`, so how do i set my own fromAddr?
if i have to compile the source code myself, is there are any guide ?

thanks,

**Comment by dom96** [comment]
oh yeah, oops. Forgot to make that configurable. 

Are you familiar with Nim at all? If so you might be able to have a try at adding support for this, the configuration is [here](https://github.com/nim-lang/nimforum/blob/master/src/utils.nim#L19), you can add a field to this type and then a line into the ``loadConfig`` procedure. 

You can then get rid of [this line](https://github.com/nim-lang/nimforum/blob/master/src/email.nim#L33) and use your newly added config field [here](https://github.com/nim-lang/nimforum/blob/master/src/email.nim#L53), i.e. something like ``mailer.config.smtpFromAddr``.

**Comment by saggit** [comment]
@dom96 Thanks for your reply, it looks simple to solve the problem, since i am totally new to nim,
I just tried to build it myself and  failed with one problem, either brew or choosenim, the newest version of Nim is `0.18.0`, but `nimforum` and `jester` require `0.18.1`, I am confused.

**Comment by dom96** [comment]
You can grab 0.18.1 by running `choosenim devel` (``brew install --head`` might also work, although that's a guess, I haven't tried it)

**Comment by saggit** [comment]
that’s really cool.
