### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by stedi67** [nim-lang/nimforum#200]
Hi,
sorry to misuse the code issue tracker for a problem on https://forum.nim-lang.org (is there a feedback email/link/form somewhere?).
I'm trying to set up an account on the forum for quite a while, but I never get any email confirmation. I'm quite sure (not a 100% though), that these email are not eaten by the spam filter. The account name would be 'stedi'.
Cheers,
Stephan
P.S.: you might want to consider to have some of these pesty legal disclaimer and notices somewhere on the forum (which might even contains some feedback email).

**Comment by dom96** [comment]
I've activated the account for you :)

**Comment by stedi67** [comment]
Thanks.
