### ISSUE TITLE
what do grayed out thread titles correspond to?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimforum#205]
![image](https://user-images.githubusercontent.com/2194784/46624615-2c572e80-cae6-11e8-9835-d12b1273fbff.png)

my understanding was that grayed out thread titles correspond to threads you're already up to date with (ie, you've seen the last post on that thread), however this isn't the case for me: some grayed out threads have new entries I haven't read yet

**Comment by dom96** [comment]
It's the CSS :visited selector, i.e. pages you've visited.
