### ISSUE TITLE
regression: css broken when loading forum in chrome

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimforum#206]
/cc @dom96 

loading https://forum.nim-lang.org/

* works with chrome incognito
* works in safari
* fails in chrome

![image](https://user-images.githubusercontent.com/2194784/47394867-4cd3db00-d6d9-11e8-876a-d84a449544c1.png)

this happened after i restarted my laptop
not sure what would be causing it; i'll try clearing cache but that's the only site for which I'm having issues

developper windows shows:
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
nimforum.css:1

**Comment by timotheecour** [comment]
fixed without having to clear cache as follows:

Hold down Ctrl and click the Reload button.

as described here: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.W8-jHWJKjyo

**Comment by dom96** [comment]
You've never seen this happen to other website's? This is a transitive issue that happens sometimes due to network issues.

**Comment by timotheecour** [comment]
>  that's the only site for which I'm having issues

in that instance (where I had ~200 tabs reopened);

well, all good now anyways.
