### ISSUE TITLE
Prohibitively slow postActivity.xml

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/nimforum#21]
`time wget 'http://forum.nimrod-lang.org/postActivity.xml' -q -O/dev/null  
0,00s user 0,00s system 0% cpu 39,923 total`
Single-threading and 40 seconds per request means that I could DoS forum from 56kbit modem.

I think that this is caused by SQLite being unable to optimize this request:

`SELECT A.id, B.name, A.content, A.thread,
    A.header, strftime('%Y-%m-%dT%H:%M:%SZ', A.creation),
    A.creation, COUNT(C.id)
    FROM post AS A, person AS B, post AS C
    WHERE A.author = B.id AND A.thread = C.thread AND C.id <= A.id
    GROUP BY A.id
    ORDER BY A.creation DESC LIMIT ?"`

I think that there is nothing inherently slow in this request, but SQLite has rather primitive optimizer (compared to MsSQL/Postgres). Maybe explicit join or subqueries will be faster?

**Comment by dom96** [comment]
Is the performance better now?
