### ISSUE TITLE
Update Nimforum to work with Nim >= 0.19.0

### ISSUE THREAD

**Issue by dvn0** [nim-lang/nimforum#211]
Nimforum currently will not compile with any recent versions of Nim. It would be great to update the code-base to support >= 0.19.0, especially with the impending 1.0 release of Nim.

I will begin work on this when I find some time in the next weeks, but I wanted to make this issue to track progress, and invite anyone else to help out.

**Comment by dvn0** [comment]
As newcomer to Nim, I am having some trouble figuring out how to modify the following line to work without the now invalid usage of `isNil` 

`template `||`(x: untyped): untyped = (if not isNil(x): x else: "")`

Source: https://github.com/nim-lang/nimforum/blob/master/src/forum.nim#L79

**Comment by Yardanico** [comment]
This template is basically not needed now, because strings are initialized by default. You can probably just remove that template and all its invocations

**Comment by jyapayne** [comment]
This should be closed via https://github.com/nim-lang/nimforum/pull/225
