### ISSUE TITLE
Cannot post because the email confirmation never arrived.

### ISSUE THREAD

**Issue by deech** [nim-lang/nimforum#213]
I can't post to the forum because the email confirmation never arrived. I tried deleting the account and re-creating with the same result. If you need to look it up my username is `deech`.

**Comment by dom96** [comment]
https://forum.nim-lang.org/profile/deech 404s

**Comment by deech** [comment]
I'm not sure what the deal is when I try and sign up again I get 
![image](https://user-images.githubusercontent.com/76703/55689288-444e2480-5948-11e9-9399-a728905280d7.png)

**Comment by dom96** [comment]
Try a different username?

**Comment by deech** [comment]
It's the standard one for all forums. Is there an issue with it?

**Comment by dom96** [comment]
I'm guessing you've signed up using it and then deleted it, so now the forum thinks it's taken.

**Comment by deech** [comment]
That's possible I don't remember. Can you possibly clear it out? I'd really like to keep it uniform.

**Comment by dom96** [comment]
Had to go into the database manually, but just for you: done :)

Your account has been resurrected and should now be usable (without the need to activate email or anything like that).

**Comment by deech** [comment]
I appreciate you going out of your way but ...
![image](https://user-images.githubusercontent.com/76703/56004957-99b16b00-5c93-11e9-8109-ccb7fa899d27.png)

**Comment by narimiran** [comment]
> I appreciate you going out of your way but ...

You can try adding `+foo` to your mail address (`aditya.siram+foo@gmail.com`). It will still arrive in your inbox (gmail ignores everything after `+`), but it might be enough to fool the forum.

**Comment by dom96** [comment]
No! You don't need to create a new account. I restored your account, the account that you've deleted. Just use it, don't create a new one!

**Comment by deech** [comment]
Works great, thanks!
