### ISSUE TITLE
Confirmation email never arrived

### ISSUE THREAD

**Issue by kidandcat** [nim-lang/nimforum#214]
I've seen it already happened (#213 ), but the confirmation email never arrived and there is no way of trigger a resend.

PD: Apart from fixing it manually, there should be a way to trigger a resend in the user side.

**Comment by dom96** [comment]
Sure. I've confirmed your account for you in the meantime.

**Comment by kidandcat** [comment]
Thank you, I'll take a look if I can help with a PR. The updated branch is master, right?

**Comment by dom96** [comment]
yep :)

**Comment by nikitavoloboev** [comment]
I have the same issue. What can I do?

**Comment by dom96** [comment]
@nikitavoloboev what's your nick?

**Comment by nikitavoloboev** [comment]
@dom96 nikivi

**Comment by dom96** [comment]
Okay, I've activated it and sent you a password reset email

**Comment by iambudi** [comment]
Hi @dom96 looks like the confirmation email issue is still happening today. 
Is it moderated by purpose or it's unresolved bug?

My nick is iambudi. Can you please activate it. 
Thank you so much in advance.

**Comment by dom96** [comment]
Maybe there is something I'm missing, but because this seems to affect only some people my bet is that this is due to some email services being very strict with how they filter emails. Have you definitely checked your spam folder?

The only way around this is to pay some service like mailchimp AFAIK, someone would need to set that up and pay for it.

**Comment by iambudi** [comment]
Yes, i did check my spam folder, it's empty. Thank you for activating my account 🙂

**Comment by geekrelief** [comment]
hi @dom96 can you confirm my account as well? user: geekrelief 
Nothing in inbox or spam. Thanks.

**Comment by dom96** [comment]
Done!

**Comment by dom96** [comment]
Emails should now come. I investigated and gmail was rejecting our emails completely. I changed the set up to use sendgrid, it will give us 100 emails/day, but that's still better than nothing.
