### ISSUE TITLE
Maybe support recaptcha.net

### ISSUE THREAD

**Issue by ringabout** [nim-lang/nimforum#227]
It's unable to visit https://www.google.com/recaptcha in China.For example, people in China can't register Nim Forum because google is banned.
So Maybe can replace this www.google.com with recaptcha.net when detected Country.

My pr in:
https://github.com/euantorano/recaptcha.nim/pull/5

Infos can be found in https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally
List below:

Can I use reCAPTCHA globally?
Yes, please use "www.recaptcha.net" in your code in circumstances when "www.google.com" is not accessible.

First, replace <script src="https://www.google.com/recaptcha/api.js" async defer></script> with <script src="https://www.recaptcha.net/recaptcha/api.js" async defer></script>
After that, apply the same to everywhere else that uses "www.google.com/recaptcha/" on your site.

**Comment by xflywind** [comment]
Now recaptcha.nim has supported www.recaptcha.net but hasn't released a new version. 
https://github.com/euantorano/recaptcha.nim/pull/5
recaptcha#3d2650f
or recaptcha#@head
