### ISSUE TITLE
Unable to activate account at https://forum.nim-lang.org/ due to error "Invalid ident hash"

### ISSUE THREAD

**Issue by qbradley** [nim-lang/nimforum#241]
I'm unable to activate my account because of error "Invalid ident hash".

Is new user registration broken?

Steps:
1. I went to https://forum.nim-lang.org/
2. I entered my email, username, and password and clicked "Create Account"
3. I received an activation link in my email
4. I clicked the link and navigated to the page
5. I clicked "Active"

The text appeared:

Invalid ident hash

Expected result:

My account was activated

When I got to my settings I still see Rank: "EmailUnconfirmed"

**Comment by qbradley** [comment]
After a while, another activation email arrived, and the subsequent link worked.

**Comment by jafd** [comment]
There was no another email for me. In fact, I've been trying with two email addresses, and none worked.

**Comment by xflywind** [comment]
@jafd hi, what's your forum name?

**Comment by jafd** [comment]
> @jafd hi, what's your forum name?
> 
> 

I've been trying to register with the same nickname as here, as well as WesolyKubeczek. I've succeeded under different nickname, but you might want to investigate why I couldn't do it with these nicknames.

I've been using email addresses with + sign in them.

**Comment by dom96** [comment]
Seems like your link just expired, closing.
