### ISSUE TITLE
Unable to sign up 

### ISSUE THREAD

**Issue by archnim** [nim-lang/nimforum#253]
Hello world. I'm trying to sign up for nim forum. But when I click on the activation link, I receive this message : invalid ident hash.
![Screenshot_20200806-042245](https://user-images.githubusercontent.com/68890552/89490969-af5a7600-d79d-11ea-9235-fe9477566e61.png)

**Comment by jyapayne** [comment]
@archnim do you know if this still happens after the forum has been upgraded?

**Comment by dom96** [comment]
FWIW I activated your account manually.

**Comment by archnim** [comment]
> FWIW I activated your account manually.

Thank you @dom96

**Comment by archnim** [comment]
> @archnim do you know if this still happens after the forum has been upgraded?

@dom96 has fixed the issue. Then i can't check anymore how the registration system works. Thank you for your concern.
