### ISSUE TITLE
Can't change category of thread after creation

### ISSUE THREAD

**Issue by digitalcraftsman** [nim-lang/nimforum#265]
Currently, it's not possible to change the category of a forum thread after it has been created, even as owner / creator of a forum thread. Instead the message "You cannot edit this thread" is shown.

Even though my current rank is just "user" at least thread owners should be able to change the category. It's easy to forget while starting a new thread. Furthermore, it would help to moderate the forum if threads can be assigned to a more suitable category such as "Question" rather than "Default".

One last note: on the *client side* the the category of a thread can be changed in the UI, even though not persistend. The error message "You cannot edit this thread" is easy to miss which leaves the user in the impression that his action suceeded.

**Comment by jyapayne** [comment]
This has already been fixed in https://github.com/nim-lang/nimforum/pull/262, although it has not been deployed yet.
