### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by unstppbl** [nim-lang/nimforum#274]
More than two years and 149 commits passed since the last v2.0.0 release, when are you planning to make a next release?

**Comment by xflywind** [comment]
v2.1.0 has been tagged and deployed https://forum.nim-lang.org/t/6725
https://github.com/nim-lang/nimforum/releases/tag/v2.1.0

**Comment by dom96** [comment]
Yeah, 2.1.0 is a release.
