### ISSUE TITLE
links followed by a closing parenthesis don't work 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimforum#285]
in nimforum, links followed by a closing parenthesis don't work (clicking on them makes the `)` part of the link), eg:
fails:
```
(see https://github.com/status-im/nim-libbacktrace/pull/10)
```
works:
```
(see https://github.com/status-im/nim-libbacktrace/pull/10 )
```

**Comment by jyapayne** [comment]
This is likely part of the RST parser in the Nim repo, nimforum just basically calls `rstgen.rstToHtml` with markdown enabled and some extra stuff for quotes and mentions

**Comment by timotheecour** [comment]
/cc @a-mr

> This is likely part of the RST parser in the Nim repo

but these work fine with both rst and nim files:

nim rst2html -r main.rst
```
fails:
(see https://github.com/status-im/nim-libbacktrace/pull/10)

works:
(see https://github.com/status-im/nim-libbacktrace/pull/10 )
```

nim doc -r main.rst

```nim
proc main*()=
  ##[
  fails:
  (see https://github.com/status-im/nim-libbacktrace/pull/10)
  works:
  (see https://github.com/status-im/nim-libbacktrace/pull/10 )
  ]##
  discard

main()
```

(as of 01bca8cd4fad857124794144bff09ae0326895bd)

**Comment by a-mr** [comment]
It's the last comma that spoils the link:

```
(http://no.org)

(http://no.org),

```

```
  rnParagraph
    rnLeaf  '('
    rnStandaloneHyperlink
      rnLeaf  'http'
      rnLeaf  ':'
      rnLeaf  '//'
      rnLeaf  'no'
      rnLeaf  '.'
      rnLeaf  'org'
    rnLeaf  ')'
  rnParagraph
    rnLeaf  '('
    rnStandaloneHyperlink
      rnLeaf  'http'
      rnLeaf  ':'
      rnLeaf  '//'
      rnLeaf  'no'
      rnLeaf  '.'
      rnLeaf  'org'
      rnLeaf  ')'
    rnLeaf  ','
```

It's an RST parser bug indeed.

**Comment by jyapayne** [comment]
@timotheecour not sure which version of nim that the nimforum is compiled with. @dom96 ?
