### ISSUE TITLE
Issue rendering code blocks with triple ticks.

### ISSUE THREAD

**Issue by ZoomRmc** [nim-lang/nimforum#318]
As seen in this message: https://forum.nim-lang.org/t/7926#51699

```
Couldn't render historic post in #51699.
```

Editing preview: `Message needs to be valid RST! Error: input(46, 1) Error: new section expected (underline '```' is too short)` The edited post is not saveable, unfortunately (#315).

The lack of an empty line before the opening triple ticks seems to be the problem. 

**Desired behaviour:** not needing an empty line before opening a new code block.

**Comment by esafak** [comment]
@a-mr In light of https://github.com/nim-lang/nimforum/pull/308, could you comment on this matter?

**Comment by a-mr** [comment]
@dom96 
[Nim 1.6.8 is out](https://nim-lang.org/blog/2022/09/27/version-168-released.html) and it contains [the fix for this problem](https://github.com/nim-lang/Nim/pull/20216).
Could you update the version on the site?

**Comment by dom96** [comment]
Done
