### ISSUE TITLE
No way of register to forum if your activation link is expired

### ISSUE THREAD

**Issue by piertoni** [nim-lang/nimforum#324]
I registered to nim forum and than waited some days before clicking the activation link on e-mail.
Obviously the link was expired, but even if I am able to enter nim forum, I cannot resend an activation link (I couldn't find option anywhere).
Without activating the account I cannot write a post.
I tried to delete the account and recreating it having some errors and finally "Too many mails were sent to this account".
Probably not a big bug, I should wait some time and try again... but still annoying and so here is the issue.

**Comment by piertoni** [comment]
It is a week that I am trying to register using different account names/emails...
Sometimes I can register, I receive the email and than cannot enter to forum.
Sometimes I don't receive e-mail (using gmail)
Sometimes I try to reset password, I successfully reset but I still cannot enter the forum.
The error given is usually: "Unknown error occurred."
I think there is something weird going on... someone can check please?

**Comment by dom96** [comment]
If you share your nick then we can activate your account on the forum. (Your non-deleted accounts please)

**Comment by piertoni** [comment]
> If you share your nick then we can activate your account on the forum. (Your non-deleted accounts please)

piertoni
Thanks

**Comment by dom96** [comment]
That account doesn't exist

**Comment by dom96** [comment]
https://github.com/nim-lang/nimforum/issues/214#issuecomment-1208616201
