### ISSUE TITLE
Cannot register in forum

### ISSUE THREAD

**Issue by rotu** [nim-lang/nimforum#325]
I’m trying to sign up in the nim forum and it does not appear to be working. I did not receive an activation email. When I enter my email for password reset, the interface says the email was sent, but I do not appear to have received it.

My username I tried to register with is “rotu”.

**Comment by dom96** [comment]
Did you delete your account? I can't find it to activate it. If you deleted it you'll need to register again with a new nick.

**Comment by rotu** [comment]
thanks. I did delete my initial account. I’ve created a new one with username “ro2”.  I don’t see an activation email nor a password reset email for the new account

**Comment by dom96** [comment]
I activated it for you.
