### ISSUE TITLE
Double quotes in title aren't escaped, or are lost

### ISSUE THREAD

**Issue by gradha** [nim-lang/nimforum#37]
The thread at http://forum.nim-lang.org/t/693/1 shows the title "**Problems with the "Download" page**". The second page at http://forum.nim-lang.org/t/693/2 shows only "**Re: Problems with the**". Looks like there is an escaping error somewhere regarding double quotes.

**Comment by dom96** [comment]
Fixed via https://github.com/nim-lang/nimforum/commit/0204aadddbe8033c1b76eb875df62fea9f110860
