### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by flaviut** [nim-lang/nimforum#41]
`.. image:: http://i.imgur.com/oCem13Y.png` should place an inline image, but it is simply ignored at the moment. See http://forum.nim-lang.org/t/812#4702 for an example. IIRC they've worked in the past. This may be a bug in Araq/Nim.

**Comment by singularperturbation** [comment]
Tested this out - can confirm that `rstgen.nim`'s renderImage (called from `rstToHtml`) is returning an empty string.  Will do a bit more digging to see if I can find out why, but I think this may need to be fixed upstream.

**Comment by singularperturbation** [comment]
Able to trace this back to validity-checking in rstgen.nim.  #3175 (https://github.com/nim-lang/Nim/pull/3175) fixes

**Comment by singularperturbation** [comment]
Hmmm... the image directive still doesn't work on the production forum (just tried).  @dom96  Do you know if the forum is using an older version of the rst module, or if the image directive is disallowed elsewhere?

I just tried my test case from ^ and I think it works...

**Comment by dom96** [comment]
Are you sure it doesn't work? It's displayed properly here: http://forum.nim-lang.org/t/812#4702

**Comment by singularperturbation** [comment]
I'll try to reproduce locally... I had tried previewing a new post with the image directive and it didn't.
