### ISSUE TITLE
Can't get it to work (after I found some stuff to fix)

### ISSUE THREAD

**Issue by oderwat** [nim-lang/nimforum#43]
When I try to compile I first get a problem because "rst" is not imported.

The cfg File seems not to work for me (obviously I do not have $nimrod defined)!

```
--path:"$nimrod/lib/packages/docutils"

--path:"$nimrod"
```

I added `path="$lib/packages/docutils"` to my `/etc/nim.cfg` and that was fixed.

I tried to do the same in `forum.nim.cfg` and it worked. So I guess that could be fixed in this repository. I would be happy to make a PR.

After that was done it complained about:

`clang: error: no such file or directory: '/Users/hara/devsys/workspace/nim/nimforum/nimcache/crypt-blowfish.o'`

I found this is because the nim bcrypt lib does not compile on OS X. I could fix that and created a pull request (https://github.com/runvnc/bcryptnim/pull/2)

After those changes I can compile with nimble build and it runs. But on the website I get this error:

```
An error has occured in one of your routes.

Detail: no such table: thread
```

I thought this could be fixed by importing the `fts.sql` I saw in the directory. Blindly trying with `sqlite3 nimforum.db < fts.sql`  gave an error. The file is obviously not what I thought :)

Here I can't continue? How to initialise the sql and get the Forum flying?

**Comment by dom96** [comment]
Did you compile and run ``createdb.nim``?

As for the other problems, do please create a PR for them.

**Comment by oderwat** [comment]
Of course I did not run or even see "createdb" ;-) ... done and works! pretty cool!

**Comment by dom96** [comment]
Something to add to the readme! :)

**Comment by oderwat** [comment]
I am just doing that PR pending

**Comment by oderwat** [comment]
Done. I hope I did not fail with wording in the readme! Also the bcrypt osx info could go away when the PR for the bcrypt library was accepted. But until then there should be no problem for mac users to fetch that from my repo.

**Comment by dom96** [comment]
Presumably I can close this now.
