### ISSUE TITLE
Forum sign up not possible

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimforum#52]
Sorry for [cross post](https://github.com/Araq/Nim/issues/2446) -- just for sake of completeness.

None of my email addresses are allowed, due to the apparent restrictions:

 - Addresses can have at most 30 characters (as a hard limit on the input box).
 - University addresses (e.g., `kit.edu`) are not accepted as a valid domain (results in: `Error: Invalid email address`).

**Comment by flaviut** [comment]
Part one is a form issue, see https://github.com/nim-lang/nimforum/blob/b7584de4407499ea30d1c5253ae797dcc5f7bc3a/forum.nim#L101-L106.

Fix would be to delete `maxlength` completely. If the field length needs to be limited, then it should be done server-side anyway, but it never should be limited (see google's behavior with too-long queries).

**Comment by dom96** [comment]
Should be fixed now.
