### ISSUE TITLE
Feature: mailing list mirroring

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimforum#57]
Every new message on the forum could be also sent to a mailing list (possibly in a way that allows threading).
It would be awsome if people could also reply to the emails on the mailing list and nimforum coulld ingest them and replicate them in the forum (effectivly mirroring the mailing list)
- [x] Forum to mailing list
- [x] Sender/Resent-From field
- [ ] Email threading
- [ ] Mailing list to forum

**Comment by FedericoCeratto** [comment]
The forum-to-mlist sync has been implemented and deployed.

**Comment by FedericoCeratto** [comment]
#62 is also related

**Comment by timotheecour** [comment]
See also: https://forum.nim-lang.org/t/989/1#23154 Is there email support for the forum

are there instructions for how to setup email forwarding?

**Comment by FedericoCeratto** [comment]
@timotheecour It's simple but you need to have access to the server running the forum to do that - unless you plan to run your own instance of the forum software.

**Comment by timotheecour** [comment]
oh, so it's not actually allowing end users to read the forum via (say) gmail? ok I see

**Comment by wavexx** [comment]
See: https://forum.nim-lang.org/t/3645/1#22734

I'm keeping a one-way forum->mail gateway going.

**Comment by wavexx** [comment]
I'm actually tempted to mirror the content to mail-archive.org to have another searchable archive too, as the gmane one no longer works. But I wonder what the current forum gatekeepers think about this.

**Comment by dom96** [comment]
As I've mentioned in a different issue, I would prefer for someone to create their own mirror separate to this forum.

**Comment by wavexx** [comment]
Also #93.
It's finally here now: https://www.mail-archive.com/nim-general@thregr.org/

**Comment by dom96** [comment]
@wavexx Awesome! Post about it on the forum :)

**Comment by dom96** [comment]
I assume it uses the RSS feed?

**Comment by wavexx** [comment]
On Mon, Aug 06 2018, Dominik Picheta wrote:
> I assume it uses the RSS feed?

Yes. It's one-way only because of this.

You can subscribe directly via nim-general+subscribe@thregr.org

The archive is at: https://www.mail-archive.com/nim-general@thregr.org/
which starts at about Jun 2016. Nicely searchable.

It's also mirrored on gmane (group gmane.comp.lang.nim.general) via NNTP.

Pick your poison ;)

I'd be glad if you make an announcement as well. I'm away at the moment
and have no credentials at hand.

**Comment by dom96** [comment]
Done: https://forum.nim-lang.org/t/4109

**Comment by wavexx** [comment]
I'm not sure where to write this, but I think very few people are aware of this option. I had an own colleague ask today fur such info.

I think a link to the list archive and maybe some instructions should be added under the main webpage, just under "threaded discussion".

Having a different domain shown (thregr.org) is also not great. I can run the list under a different domain if an appropriate MX record is added (say, lists.nin-lang.org). I'm fully flexible here.

But I have no idea to whom I would ask this.
I can also provide the script I'm using to generate the mirror if any of the current maintainers wants to run the mailing list under direct control. As long as it's a one-way mirror, there's no complicated setup to do.

**Comment by dom96** [comment]
I'm happy to add this record. Just let me know what it should point at.

**Comment by wavexx** [comment]
On Wed, Sep 19 2018, Dominik Picheta wrote:
> I'm happy to add this record. Just let me know what it should point at.

MX 10 mx.thregr.org

The list name is also flexible. It's currently "nim-general", as this
maps the gmane hierarchy it's mapped on. But with the proper domain
name, I think we can safely do nim@lists.nim-lang.org

I'll take care of moving the old names.

**Comment by wavexx** [comment]
Ping @dom96

**Comment by dom96** [comment]
Sorry about the delay. The MX record has been added.

<img width="966" alt="screen shot 2018-09-30 at 20 57 20" src="https://user-images.githubusercontent.com/246651/46269071-72fbc600-c4f3-11e8-9ed4-f72b8705d06c.png">

**Comment by wavexx** [comment]
Wow, I was even slower, but I updated the list details and did some switcheroo.
The list is now using and advertising nim-general@lists.nim-lang.org

Subscription/unsubscription is using the standard nim-general+subscribe@ and nim-general+unsubscribe@

The gmane archive gmane.comp.lang.nim.general and the archive at mail-archive.com already work, although I requested to update the list-info details to match the new domain.

**Comment by wavexx** [comment]
@dom96 hijacking this again. Looking at my logs, I'm seeing some new rejects from google due to the missing spf record. Can you also add a txt record on `lists.nim-lang.org` with the simple rule `v=spf1 mx -all`?

**Comment by dom96** [comment]
@wavexx I'm not involved with Nim anymore these days
