### ISSUE TITLE
Confirmation email

### ISSUE THREAD

**Issue by AnyCPU** [nim-lang/nimforum#61]
No confirmation email after registration.

**Comment by dom96** [comment]
What's your nickname on the forum?

**Comment by AnyCPU** [comment]
I think should be 'AnyCPU'.

**Comment by dom96** [comment]
Nope: http://forum.nim-lang.org/profile/AnyCPU

**Comment by AnyCPU** [comment]
Please check email address that ends with "@m1xa.com".

**Comment by dom96** [comment]
Please tell me what nickname you registered with, or register again if you can't remember.

**Comment by AnyCPU** [comment]
Just now - AnyCPU, 
>You are now registered. You must now confirm your email address by clicking the link.
And no email.

**Comment by dom96** [comment]
Send me an email (from the email you registered with) to dom[at]picheta{dot}me

**Comment by dom96** [comment]
Assuming this is now solved?
