### ISSUE TITLE
Compilation error with nimforum, Nim 0.12.1

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/nimforum#70]
```
...
ast.nim(1245)            sonsLen
system.nim(2533)         sysFatal
Error: unhandled exception: sons is not accessible [FieldError]
FAILURE: Build failed for package: nimforum
```

On Linux AMD64 with `f3814be5305743b` version of Nim

**Comment by singularperturbation** [comment]
Found that this is actually a compiler crash, and was able to isolate it to trying to get open array length and then crashing.  I'll create an issue in nim-lang/Nim and follow up there.

### Background:
Through experimenting, I  found that it's due to https://github.com/nim-lang/nimforum/blob/master/forum.nim#L1302-L1305:
```{nimrod}
let basePath =
  if path[path.high] == '/': path & "index"
  elif path.endsWith(".html"): path[^5 .. ^1]
  else: path
```
The `path[^5 .. ^1]` part leads to the crash - removing it has the forum compile without complaint.  I think that the "roof" operator is rewriting to path.len, and then somehow it's forgetting that path is a string and not an openarray based on following the stack trace:

```
semfold.nim(693)         getConstExpr
semfold.nim(507)         magicCall
semfold.nim(295)         evalOp
ast.nim(1251)            sonsLen
system.nim(2533)         sysFatal
Error: unhandled exception: sons is not accessible [FieldError]
```

**Comment by dom96** [comment]
Will close since its specific to Nim
