### ISSUE TITLE
Feature request: View for comments / threads submitted by user

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/nimforum#85]
Should be able to view comments / titles of threads submitted by user in the user's profile.  

I'll start working on this if no objections. :)

**Comment by dom96** [comment]
Go for it :)

**Comment by jlp765** [comment]
Should that also be a link when you view a person's profile  (view the threads they have written, view posts they have made)?

**Comment by timotheecour** [comment]
can we use something close to github syntax? it's nice and easy to extend; eg:

`author:foo involves:foo`

**Comment by dom96** [comment]
This is solved in the ``redesign`` branch.
