### ISSUE TITLE
Mailing list mirroring broken

### ISSUE THREAD

**Issue by stisa** [nim-lang/nimforum#93]
Looks like mailing list mirroring has been broken since the beginning of January:  
first broken post: http://www.freelists.org/post/nim-dev/Nim-threads-vs-Pthreads

Looks like it does not allow html posts anymore?
Maybe there's an option to set on the mailing list: http://www.freelists.org/wiki/faq/enable_html
Or we should just send plain rst (without converting to html).

**Comment by dom96** [comment]
I'm afraid I'll be discontinuing this feature. If somebody wants to implement mirroring they will be able to still do so much more easily soon enough in a separate tool. The forum is getting a redesign and posts/threads will be easily parseable (JSON).
