### ISSUE TITLE
Posting gives me bounce messages from MAILER-DAEMON@nim-lang.org

### ISSUE THREAD

**Issue by noxpo** [nim-lang/nimforum#97]
Contained error message from nim-dev@freelists.org (forum mirror?):

<nim-dev@freelists.org>: host turing.freelists.org[206.53.239.180] said: 450
    4.7.1 Client host rejected: cannot find your hostname, [178.62.143.63] (in
    reply to RCPT TO command)

Since 178.62.143.63 is nim-lang.org, this looks as if freelists.org chokes on forum-generated mails.
Probably related to #93.

**Comment by dom96** [comment]
Sadly I don't really have the time to look into this issue (or the will to be honest). Maybe I can disable the mailing list feature if these bounces are too annoying.

**Comment by noxpo** [comment]
Don't kill the feature because of me, I'll just pretend I don't see them..

**Comment by flyx** [comment]
I have the same issue. Please note that sending people unwanted (i.e. spam) e-mails is illegal in most countries. Therefore, if this cannot be fixed, the mailing list feature should be disabled.

**Comment by dom96** [comment]
Alright. I disabled it. Let me know if there are any more bounces.
